### DISCUSSION TITLE
Dashboard card for toggle position of curtains

### DISCUSSION THREAD

**Discussion by saenzramiro** [hsakoh/switchbot-mqtt#45] [Q&A]
Thanks for making this add-on! Lifesaver!

I'm trying to add a card to my dashboard where I can toggle the position of my curtains. I have almost all of them working in parallel with the other (grouped) so every time I open/close one, it will open/close the other. This works perfect if I run the commands turnOn/turnOff of the primary curtain.

How can I create a card to toggle the position of the curtain? If the position is 100%, needs to run the setPosition to 0% and biceversa.

**Comment by saenzramiro** [comment]
I think the best way will be to create like a new device/helper so it can also work with Assist or Google Home.

Am I right?

**Comment by hsakoh** [comment]
Thank you for the feedback.
Regarding the use of Home Assistant, it doesn't seem to be an issue with the add-on, so I'll convert this into a discussion.

**Comment by hsakoh** [comment]
I don't have grouped curtains, so I can't verify it, but I think I can offer some advice.

To rephrase what you want to achieve, I believe it's about "changing the value of mqtt.input based on certain conditions" and "pressing a button," all in a single action.

### When performing this as an operation on the control

The action from the color bulb template might be helpful as a reference. #1
https://gist.github.com/hsakoh/6dc11caf959a0350d50fc3ba4be943d4#file-configuration-yaml

* You can obtain the current value using an expression like `states('sensor.both_brightness_XXXXXXXXXXXX')`.

* You can set a value for mqtt.number with a expression like this:
```
- service: number.set_value
  target:
    entity_id: number.colortemperature_6_cmd_XXXXXXXXXXXX
  data:
    value: "{{ ((1-(color_temp-153)/(500-153))*(6500-2700)+2700)|int }}"
```

* You can press mqtt.button with a expression like this:
```
- service: button.press
  data:
    entity_id: button.btn_6_cmd_XXXXXXXXXXXX
```

### When sending MQTT messages directly to the add-on for control

When you operate mqtt.input, number, or button prepared by the add-on, it publishes MQTT messages.

I have provided specific examples of topics and payloads here:
https://github.com/hsakoh/switchbot-mqtt/wiki/InternalArchitecture#device-command-topic

You can check the actual MQTT messages from the MQTT INFO of each device in the MQTT integration.

Once you've identified the MQTT message you want to send, I think you can send it directly with a expression like this:
```
action: call-service
service: mqtt.publish
service_data:
  topic: switchbot/FFF921xxxxxx/cmd
  payload: '{"CommandType": "command","Command": "setPosition","ParamValue": "100"}'
```

**Reply by hsakoh** [reply]
https://github.com/hsakoh/switchbot-mqtt/discussions/23

**Comment by saenzramiro** [comment]
Thank you for the quick answer!

I will try to accomplish this with all the information you gave me and share with you the results.

**Comment by saenzramiro** [comment]
Ok, so after learning a lot about HA and your help, I could get something functional to use my curtains.
I want to share my code:

`configuration.yaml`
```
cover:
  - platform: template
    covers:
      cortina_oficina_tpl:
        unique_id: cortina_oficina_tpl
        friendly_name: "Cortina Oficina"
        device_class: curtain

        # Usar el macro para el estado
        value_template: >-
          {% if is_state('sensor.both_slideposition_ff955b88901a', 'unknown') %}
            unknown
          {% elif states('sensor.both_slideposition_ff955b88901a') | int >= 90 %}
            closed
          {% elif states('sensor.both_slideposition_ff955b88901a') | int <= 10 %}
            open
          {% else %}
            unknown
          {% endif %}

        # Usar el macro para el icono
        icon_template: >-
          {% if is_state('sensor.both_slideposition_ff955b88901a', 'unknown') %}
            mdi:alert-box-outline
          {% elif states('sensor.both_slideposition_ff955b88901a') | int >= 90 %}
            mdi:curtains-closed
          {% elif states('sensor.both_slideposition_ff955b88901a') | int <= 10 %}
            mdi:curtains
          {% else %}
            mdi:loading
          {% endif %}

        # Usar el macro para la posición de la cortina
        position_template: "{{ states('sensor.both_slideposition_ff955b88901a') | int }}"

        # Comando para abrir la cortina usando el script parametrizado
        open_cover:
          - service: script.open_cover_script
            data:
              device_id: "ff955b88901a"
              button_id: "3"

        # Comando para cerrar la cortina usando el script parametrizado
        close_cover:
          - service: script.close_cover_script
            data:
              device_id: "ff955b88901a"
              button_id: "2"

        # Comando para detener la cortina usando el script parametrizado
        stop_cover:
          - service: script.stop_cover_script
            data:
              device_id: "ff955b88901a"
              button_id: "4"

        # Usar el script para set_cover_position
        set_cover_position:
          - service: script.set_cover_position_script
            data:
              device_id: "ff955b88901a"
              position: "{{ position }}"
```

`scripts.yaml`
```
open_cover_script:
  description: "Abrir cortina con ID del dispositivo parametrizado"
  fields:
    device_id:
      description: "ID del dispositivo"
      example: "ff955b88901a"
      required: true
    button_id:
      description: "ID del botón"
      example: "3"
      required: true
  sequence:
    - service: button.press
      target:
        entity_id: "button.btn_{{ button_id }}_cmd_{{ device_id | lower }}"
    - delay: 20
    - service: button.press
      target:
        entity_id: "button.update_{{ device_id | lower }}"
close_cover_script:
  description: "Cerrar cortina con ID del dispositivo parametrizado"
  fields:
    device_id:
      description: "ID del dispositivo"
      example: "ff955b88901a"
      required: true
    button_id:
      description: "ID del botón"
      example: "2"
      required: true
  sequence:
    - service: button.press
      target:
        entity_id: "button.btn_{{ button_id }}_cmd_{{ device_id | lower }}"
    - delay: 20
    - service: button.press
      target:
        entity_id: "button.update_{{ device_id | lower }}"
stop_cover_script:
  description: "Detener cortina con ID del dispositivo parametrizado"
  fields:
    device_id:
      description: "ID del dispositivo"
      example: "ff955b88901a"
      required: true
    button_id:
      description: "ID del botón"
      example: "4"
      required: true
  sequence:
    - service: button.press
      target:
        entity_id: "button.btn_{{ button_id }}_cmd_{{ device_id | lower }}"
    - delay: 3
    - service: button.press
      target:
        entity_id: "button.update_{{ device_id | lower }}"
set_cover_position_script:
  description: "Script para establecer la posición de la cortina con ID del dispositivo parametrizado"
  fields:
    device_id:
      description: "ID del dispositivo"
      example: "ff955b88901a"
      required: true
    position:
      description: "Posición de la cortina"
      example: "50"
      required: true
  sequence:
    - service: mqtt.publish
      data_template:
        topic: switchbot/{{ device_id | upper }}/cmd
        payload: >
          {
            "CommandType": "command",
            "Command": "setPosition",
            "ParamName": "position",
            "ParamValue": "{{ position }}"
          }
    - delay: 3
    - service: mqtt.publish
      data_template:
        topic: switchbot/{{ device_id | upper }}/cmd
        payload: >
          {
            "ParamName": "position",
            "CommandType": "command",
            "Command": "setPosition",
            "ParamName": "btn",
            "ParamValue": "action"
          }
    - delay: 20
    - service: button.press
      target:
        entity_id: "button.update_{{ device_id | lower }}"
```


I only have one problem that makes the curtains state and position unstable and uncompleted:
1. I don't know why sometimes it shows *Open* and the _slidePosition_ returns 100, which should be *Closed*. I'm sure I'm doing something wrong.
2. I cannot display *Closing* and *Opening* states. Any ideas?

**Reply by hsakoh** [reply]
It seems that the issue is caused by a difference between the cover template and the API values.

The slidePosition in the API and Webhook ranges from 0 to 100, where 0 is open, and 100 is closed. However, in the cover template, the range is also 0-100, but 0 is closed, and 100 is open.

So, I thought that in the position template, using 100 - state, and in the set_cover_position action, using 100 - position might work well.

```yaml
        # Usar el macro para la posición de la cortina
        position_template: "{{ 100-(states('sensor.both_slideposition_ff955b88901a') | int) }}"

        # Usar el script para set_cover_position
        set_cover_position:
          - service: script.set_cover_position_script
            data:
              device_id: "ff955b88901a"
              position: "{{ 100 - position }}"
```
