### ISSUE TITLE
S10 vacuum: Not receiving webhooks from API

### ISSUE THREAD

**Issue by abx360** [hsakoh/switchbot-mqtt#27]
First of all thank you for your work, which is making almost perfect my S10 vacuum 🤗

Anyway, I'm not receiving any updates from the webhooks, only active polling is working.

This is my configuration:
- Docker container v1.0.18
- Not using ngrok
- open port 8098 in the container (8098:8098)
- using Caddy as https reverse proxy

This is my Compose config:
```
  switchbotmqtt:
    container_name: switchbotmqtt
    image: ghcr.io/hsakoh/switchbotmqtt-amd64:1.0.18
    networks:
      - domotica_network
    ports:
      - "8098:8098"
      - "8199:8099" #8099 port used
    volumes:
      - ./switchbotmqtt:/data
    restart: unless-stopped
```
And this the webhook configuration:
```
    "WebhookService": {
      "UseWebhook": true,
      "UseNgrok": false,
      "NgrokAuthToken": "NA",
      "HostUrl": "https://sbmqtt.xxmysitexx.it"
    }
```
Of course also the webhook is ticked in the device configuration, and the webhook service started.

If I call the webook with curl or even https://reqbin.com/, I see that the service and the configuration are fine, since I can change the shown values (eg battery%) in home assistant:
`curl -H "Content-Type: application/json" -X POST https://sbmqtt.xxmysitexx.it/webhook -d '{"eventType":"changeReport","eventVersion":"1","context":{"deviceMac":"123456789","deviceType":"WoSweeperOrigin","workingStatus":"ChargeDone","onlineStatus":"online","battery":100,"waterBaseBattery":100,"taskType":"standBy","timeOfSample":1715158038876}}'`
The values are changing and in the logs I can see:
`switchbotmqtt  | 13:07:10 info: SwitchBotMqttApp.Controllers.WebhookController[0] {"eventType":"changeReport","eventVersion":"1","context":{"deviceMac":"123456789","deviceType":"WoSweeperOrigin","workingStatus":"ChargeDone","onlineStatus":"online","battery":100,"waterBaseBattery":100,"taskType":"standBy","timeOfSample":1715158038876}}`

I also verified the SwitchBot API configuration, and it seems ok.
If i send this command to check the webhook configuration: 
`curl -H "Content-Type: application/json" -H "Authorization: XXmykeyXX" -X POST https://api.switch-bot.com/v1.0/webhook/queryWebhook -d '{"action":"queryDetails", "urls":"https://sbmqtt.xxmysitexx.it/webhook"}`
The API replies:
`{"statusCode":100,"body":[{"deviceList":"ALL","createTime":1719941450906,"url":"https://sbmqtt.xxmysitexx.it/webhook","enable":true,"lastUpdateTime":1719941450906}],"message":"success"}`

Am I missing something? 🤔
