### ISSUE TITLE
add some mqtt payload demo

### ISSUE THREAD

**Issue by fireport** [hsakoh/switchbot-mqtt#33]
I struggle to find the mqtt payload to set a disposable pin on my keypad Pro.
Using the test page is fine but having the corresponding generated payload should be nice.
Some automation examples should be nice too.

**Comment by fireport** [comment]
Following your hints I tried to execute the code in this YAML but unfortunately without luck.
Can you help me ?

```

action:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\": \"name\", \t\"ParamValue\": \"topolino\" }"
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\":  \"type\", \t\"ParamValue\": \"disposable\" }"
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\": \"password\", \t\"ParamValue\": \"123456\" }"
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\": \"startTime\", \t\"ParamValue\": \"1722770320\" }"
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\": \"endTime\", \t\"ParamValue\": \"1722773920\" }"

```

**Comment by hsakoh** [comment]
The input is correctly done. I believe the "button pressed" message is missing.
(For curtains, it's 3 parameters + "button pressed" for a total of 4 messages.
For the keypad, it should be 5 parameters + "button pressed" for a total of 6 messages.)
![image](https://github.com/user-attachments/assets/86741ca3-8c96-444f-b9b3-40974dd597d6)

What happens if you send the following message at the end?

```
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: switchbot/XXXXXXXXXXXX/cmd
      payload: "{ \t\"CommandType\": \"command\", \t\"Command\": \"createKey\", \t\"ParamName\": \"btn\", \t\"ParamValue\": \"action\" }"
```
