### ISSUE TITLE
KeyNotFoundException when sending MQTT command

### ISSUE THREAD

**Issue by rcoundon** [hsakoh/switchbot-mqtt#71]
I have defined an automation that looks like this:

```yaml
- id: '1739792840432'
  alias: Test Switchbot
  description: ''
  triggers:
  - trigger: mqtt
    topic: switchbot/FA0B5F22400D/status
  conditions: []
  actions:
  - action: input_text.set_value
    metadata: {}
    data:
      value: '{{ trigger.payload }}'
    target:
      entity_id: input_text.switchbot_sensor_output
  - action: mqtt.publish
    data:
      topic: "switchbot/C43430373B47/cmd"
      payload: "{ \"CommandType\": \"command\", \"Command\": \"press\", \"ParamValue\": \"default\" }"
  mode: single

```
With the ultimate aim of triggering a Switchbot button press when humidity rises above a certain level.
When this automation triggers I get the following error in the log:

```
12:53:15 fail: SwitchBotMqttApp.Services.MqttCoreService[0] subscribe action C43430373B47,{ "CommandType": "command", "Command": "press", "ParamValue": "default" } System.Collections.Generic.KeyNotFoundException: The given key 'C43430373B47' was not present in the dictionary.    at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)    at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)    at SwitchBotMqttApp.Services.MqttCoreService.ReceiveCommandAsync(String payloadRaw, DeviceBase device) in C:\github\hsakoh\switchbot-mqtt\src\SwitchBotMqttApp\Services\MqttCoreService.cs:line 362
```

Is there something that needs to be done to ensure that the devices and IDs are recognised?  I see them all in the Web UI for the addon.

Thanks
